### Bibliotheken importieren

In [3]:
import numpy as np
import matplotlib as plt

### variablen setzen

In [4]:
e = np.exp(1)
pi = np.pi
i = 1j

### Aufgabe A:

In [5]:
print(1*2**3+5)

13


### Aufgabe B:

In [6]:
e**(i*pi) 

(-1+1.2246467991473532e-16j)

Rundungsfehler bei Aufgabe B aufgrund von Python

### Aufgabe C:

In [10]:
z = 3+i*5

### Aufgabe D:

In [13]:
spaltenVek = np.array(([1],[2],[3]))
ones = np.ones((3,4))
print(ones * spaltenVek)

[[1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]]
