### importieren von bibliotheken

In [2]:
import numpy as np
import matplotlib as plt

### Variablen setzen

In [3]:
e = np.exp(1)
pi = np.pi
i = 1j

### aufgaben

In [19]:
print(1*2**3+4)
e**(i*(pi/2))
z = 1+i*2
print(np.matrix(([1],[2],[3]))*np.ones(3))

12
[[1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]
