### Faltung


In [1]:
#Faltungsrechner
import numpy as np
import scipy.signal as sig

def lineareFaltungRechner(a,b):
    faltung = np.convolve(a,b)
    print("Faltungsergebnis:", np.flipud(a),"*",b,"=",faltung)

    #Rechnungsdarstellung als Matrix
    l = a.size + b.size -1 #länge des erbegnisarrays
    a = np.append(np.flipud(a), np.zeros(l-a.size))
    b = np.insert(b, 0, np.zeros(l-b.size))
    print("")
    print("Rechnungsdarstellung: a * b")
    for i in range(l):
        if (i == 0):
            temp = "  ="
            for g in range(len(a)):
                if (a[g] == 0 or b[g] == 0):
                    pass
                else:
                    if (temp == "  ="):
                        str1 = a[g],"*",b[g]
                        temp = " = "+str(str1)
                    else:
                        str1 = a[g],"*",b[g]
                        temp = temp+"+"+str(str1)
            print(a, " [",b[i],"] = [",faltung[i],"]", temp)
            #print(temp)
        else:
            a = np.insert(a, 0, np.zeros(1))
            a = a[:-1]
            temp = "  ="
            for g in range(len(a)):
                if (a[g] == 0 or b[g] == 0):
                    pass
                else:
                    if (temp == "  ="):
                        str1 = a[g],"*",b[g]
                        temp = " = "+str(str1)
                    else:
                        str1 = a[g],"*",b[g]
                        temp = temp+"+"+str(str1)
            
            print(a, " [",b[i],"] = [",faltung[i],"]", temp)

# Beispiel

In [4]:
x_1 = np.array([1,3,-2,-1,1,3,-2,-1])
x_2 = np.array([1,2,3])
lineareFaltungRechner(x_2,x_1)

Faltungsergebnis: [3 2 1] * [ 1  3 -2 -1  1  3 -2 -1] = [ 1  5  7  4 -7  2  7  4 -8 -3]

Rechnungsdarstellung: a * b
[3. 2. 1. 0. 0. 0. 0. 0. 0. 0.]  [ 0 ] = [ 1 ]  = (1.0, '*', 1)
[0. 3. 2. 1. 0. 0. 0. 0. 0. 0.]  [ 0 ] = [ 5 ]  = (2.0, '*', 1)+(1.0, '*', 3)
[0. 0. 3. 2. 1. 0. 0. 0. 0. 0.]  [ 1 ] = [ 7 ]  = (3.0, '*', 1)+(2.0, '*', 3)+(1.0, '*', -2)
[0. 0. 0. 3. 2. 1. 0. 0. 0. 0.]  [ 3 ] = [ 4 ]  = (3.0, '*', 3)+(2.0, '*', -2)+(1.0, '*', -1)
[0. 0. 0. 0. 3. 2. 1. 0. 0. 0.]  [ -2 ] = [ -7 ]  = (3.0, '*', -2)+(2.0, '*', -1)+(1.0, '*', 1)
[0. 0. 0. 0. 0. 3. 2. 1. 0. 0.]  [ -1 ] = [ 2 ]  = (3.0, '*', -1)+(2.0, '*', 1)+(1.0, '*', 3)
[0. 0. 0. 0. 0. 0. 3. 2. 1. 0.]  [ 1 ] = [ 7 ]  = (3.0, '*', 1)+(2.0, '*', 3)+(1.0, '*', -2)
[0. 0. 0. 0. 0. 0. 0. 3. 2. 1.]  [ 3 ] = [ 4 ]  = (3.0, '*', 3)+(2.0, '*', -2)+(1.0, '*', -1)
[0. 0. 0. 0. 0. 0. 0. 0. 3. 2.]  [ -2 ] = [ -8 ]  = (3.0, '*', -2)+(2.0, '*', -1)
[0. 0. 0. 0. 0. 0. 0. 0. 0. 3.]  [ -1 ] = [ -3 ]  = (3.0, '*', -1)


#### faltungslänge

In [3]:
L_1 = 21
L_2 = 41

print(L_1 + L_2-1)

print("Faltungsergebnis:", sig.convolve(x_2,x_1))

61
Faltungsergebnis: [ 1  5  7  4 -8 -3]
